services:
  - type: web
    name: chatbot-laponia-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GROQ_API_KEY